### ISSUE TITLE
[Bug] Export to PDF broken

### ISSUE THREAD

**Issue by Proshyak** [SlRvb/Obsidian--ITS-Theme#133]
### Infobox missing when exported as PDF with any ITS theme.
no other plugins enabled.
Obsidian keeps loading "preparing PDF" without any progress.
Using SIRvb D&D does **NOT** have the same issue.
SIRvb does output a PDF, but omits anything in the !9infobox].

**Expected behavior**
Obsidian exports the note to PDF as is.

### To Reproduce
1. Create any note with an ![infobox]
2. Settings>Export to PDF

### Screenshots
Note used for testing (with WOTC theme):
![image](https://user-images.githubusercontent.com/8677038/189157340-048df2c1-9d9e-469c-9989-db33c6c51d89.png)
![image](https://user-images.githubusercontent.com/8677038/189157421-35388a18-757c-4d7e-8655-1ce5ad12f814.png)
Output PDF exported with SlRvB theme and an infobox that didn't render:
![image](https://user-images.githubusercontent.com/8677038/189158460-644b0ee2-03eb-46fc-9f00-cb439403e8be.png)
same note exported with Cybertron Dark:
![image](https://user-images.githubusercontent.com/8677038/189159003-c995f760-6c98-4463-9ecb-f31d8bf1aea9.png)

### OS
Where does the bug occur?
Windows 10
- [X ] Desktop
- [ ] Mobile

Obsidian Version:
v0.15.9

**Comment by SlRvb** [comment]
I think I've pushed out a fix for this. Do update my theme and let me know if the export works 👀

**Comment by emiko1412** [comment]
Hello! This problem is still occurring after I updated the ITS theme. I have no other community plugins installed.

### OS

Where does the bug occur?
Windows 11
[X] Desktop
[ ] Mobile

Obsidian Version:
v0.15.9

The export to PDF function can sometimes make Obsidian stop responding, and the resulting PDF file contains everything but the infobox. The PDF file also has thousands of blank pages added to it.

In obsidian using source mode
![error2](https://user-images.githubusercontent.com/69669364/194504134-2bd877bd-0e00-40af-aaf9-09edafc43002.png)

The exported PDF
![error1](https://user-images.githubusercontent.com/69669364/194504145-5d40c6ca-4b31-4b0b-86ee-dad449f8c735.png)

**Comment by brandon-kohn** [comment]
Happens to me too with all the latest updates.

**Comment by SlRvb** [comment]
Is this still an issue on the beta?

**Comment by brandon-kohn** [comment]
Seems to be working with the beta.
