### ISSUE TITLE
[Bug] [Beta] Fantasy Statblocks Multiple Words Line

### ISSUE THREAD

**Issue by d3Xrr** [SlRvb/Obsidian--ITS-Theme#191]
### Describe the bug
Fantasy statblocks with multiple words in heading appear with an line that isn't there in live version.

**Expected behavior**
The line should not appear at all.

### To Reproduce
1. Generate statblock in obsidian

### Screenshots
![image](https://user-images.githubusercontent.com/129934266/231394388-228b4e75-5322-4bff-84a2-fe22579f5c8a.png)

**Comment by SlRvb** [comment]
Fixed #172

**Comment by d3Xrr** [comment]
Hello, it seems the line moved few inches to the right, but it still appears.
![image](https://user-images.githubusercontent.com/129934266/232685966-c2f2656a-a700-453a-a8bc-6c3cc921c513.png)

**Comment by SlRvb** [comment]
Is this on the beta version of the theme? I can't recreate this issue in the beta on my end 🤔

**Comment by SlRvb** [comment]
oh no no, that's not how you're meant to install the beta. Use the brat plugin as instructed here: https://publish.obsidian.md/slrvb-docs/ITS+Theme/ITS+Theme

**Comment by d3Xrr** [comment]
Okay sorry, im complete noob to obsidian and github. Just loved the new version so I downloaded the beta. Is there a way to have alternative dnd theme in beta ?

**Comment by SlRvb** [comment]
It's in the style settings of the theme.

**Comment by d3Xrr** [comment]
Thank you. I know about style settings, however when I set it this way it looks like this - 
![image](https://user-images.githubusercontent.com/129934266/234587755-1165f52f-0ab8-4f28-89dd-c72d90e8ee4b.png)

When I use the _Theme - All Alternate Themes_ snippet it changes all fonts and links to style of dnd books. I don't know if I'm missing something, but I cant replicate this look just trough style settings.

Sorry for bothering you. Theme looks really nice otherwise, great work!

**Comment by SlRvb** [comment]
You need this snippet for fonts: https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/Snippets/S%20-%20Encoded%20Fonts.css

**Comment by d3Xrr** [comment]
I downloaded fonts, icons and alt colors and finally achieved the look i got from those old snippets. Thank you very much for the help, bought you a coffee for answering my noob questions ;)
