### ISSUE TITLE
[Bug] Live Preview mode hides tag in `[key:: tag]`

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#268]
### Describe the bug
Live Preview mode hides the tag inside `[key:: tag]`

**Expected behavior**
Live Preview mode should not hide the tag inside `[key:: tag]`

### To Reproduce
1. Type `key:: tag`
2. Turn on Live Preview mode
3. See error

### Screenshots
**Live Preview mode in ITS theme**
![2024-01-15_00 49 21_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/4e983849-b2fb-4317-a68f-f24a7e029844)

**Source mode in ITS theme**
![2024-01-15_00 49 53_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/ae3d7c01-c9b8-4d68-855a-33729b4cf4b4)

**Live Preview mode in default** it works just fine in default theme
![2024-01-15_00 49 37_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/7dff3b93-caa6-4472-b973-1ea0efca0d6a)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: v1.5.3
- ITS Theme Version: 1.2.19

**Comment by SlRvb** [comment]
Should be fixed now in v1.2.20!

**Comment by Missionary2112** [comment]
I updated to the version v1.2.20 but the bug still persists. 
![2024-01-17_15 47 42_CSX|200](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/e5e7e2e5-b2fe-4f6c-984a-ac0ddab28c2d)
![2024-01-17_15 48 03_CSX|200](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/4c03e19f-ad17-4b15-b2a1-b08327d71a3e)

**Comment by SlRvb** [comment]
I think this should be fixed in ITS v1.2.24, do let me know if it works or not 🙈

**Comment by Missionary2112** [comment]
Yes, it works! Thank you so much for fixing it 👍
